pipeline{
    agent any
    tools{
      maven 'M2_HOME'
    }
    stages{
      
       stage("upload artifact"){
          steps{
           sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
           target/bio*.jar "http://ec2-54-236-45-108.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio__${BUILD_ID}.jar"'
           }
      }
    
    }
}